### PR TITLE
Pull from Ladicle/gojson

### LINKED ISSUE #48: Removing the vendor directory
I personally think that the vendor directory should be removed, because it'll be either duplicated with the current YAML package that we currently have, or out of sync with it. 

Either case, it make little sense to keep it there, IMO. 

Please consider. Thx.

### PR DESCRIPTION
**Pull request by suntong**
The recent work done by Ladicle/gojson seems to be interesting, and would be helpful for people in general.

*CAUTION* this PR also close #48!

### CODE REVIEW

**Comment by suntong** [comment]
"AppVeyor build failed" is a false alarm. See
https://travis-ci.org/ChimeraCoder/gojson/jobs/254457297

**Comment by ChimeraCoder** [comment]
It doesn't look like a false alarm - with the vendored code gone, the package is indeed missing, so it can't build.

**Comment by suntong** [comment]
Actually, the package missing from the vendor directory, doesn't mean the project can't be build. The Travis CI builds just fine. What's wrong is the setup of the AppVeyor build. But anyway, that's not the point now, since the vendor directory is to stay. 

So, again, the recent work done by Ladicle/gojson seems to be interesting, and would be helpful for people in general. And that's what my current code is based on. However, you have to merge it on your own now, as I've _completely_ remove the vendor directory from my `git` _history_. Hmm..., maybe that's irrelevant, but I didn't know how to remove one step to make a PR, and I still don't know until now.

**Comment by suntong** [comment]
All you need to do is to 

- merge changes from his code, then
- Revert 382269c 

So it should be pretty straightforward.

**Comment by suntong** [comment]
Closing this PR

**Comment by ChimeraCoder** [comment]
> Actually, the package missing from the vendor directory, doesn't mean the project can't be built.

It can be built, but not deterministically *from the source*. In the unlikely event that the `gopkg.in` vanished, or the `yaml.v2` package introduced a regression or breaking changes, it wouldn't be possible to clone the gojson repository by itself and build the project, because the `yaml.v2` package would be missing, and we wouldn't know which version gojson was supposed to be built against.

Put another way: we should be able to build `gojson` from source given nothing but a tarball of the source repository and a working Go compiler, with no network connection.


> I didn't know how to remove one step to make a PR, and I still don't know until now.

If I understand the question correctly, you can do `git rebase -i` to reorder and/or remove commits from a branch.

**Pull request closed without merging**
